from __future__ import annotations

import logging
from functools import lru_cache
from typing import Any, Dict

from twilio.base.exceptions import TwilioException
from twilio.rest import Client

logger = logging.getLogger("wildfire.notifications")
if not logger.handlers:
  handler = logging.StreamHandler()
  formatter = logging.Formatter("[%(asctime)s] %(levelname)s %(message)s")
  handler.setFormatter(formatter)
  logger.addHandler(handler)
logger.setLevel(logging.INFO)
logger.propagate = False


@lru_cache(maxsize=1)
def get_twilio_client() -> Client | None:
  if not all([TWILIO_SID, TWILIO_TOKEN, TWILIO_FROM, TWILIO_TO]):
    logger.debug("Twilio configuration incomplete; alerts disabled.")
    return None

  try:
    return Client(TWILIO_SID, TWILIO_TOKEN)
  except Exception as exc:
    logger.error("Failed to initialise Twilio client: %s", exc)
    return None


from .config import (
  FIRE_ALERT_THRESHOLD,
  TWILIO_FROM,
  TWILIO_SID,
  TWILIO_TOKEN,
  TWILIO_TO,
  TWILIO_VOICE_STATUS_CALLBACK,
  TWILIO_VOICE_URL,
)


def _format_number(value: Any, decimals: int = 0) -> str:
  try:
    number = float(value)
  except (TypeError, ValueError):
    return "unknown"
  if decimals == 0:
    return f"{number:.0f}"
  return f"{number:.{decimals}f}"


def _build_voice_message(confidence: float, features: Dict[str, Any]) -> str:
  pm25 = _format_number(features.get("pm25"), 1)
  pm10 = _format_number(features.get("pm10"), 1)
  aqi = _format_number(features.get("aqi"))
  temperature = _format_number(features.get("temperature_f"), 1)
  humidity = _format_number(features.get("humidity_percent"))
  wind_speed = _format_number(features.get("wind_speed_mph"), 1)
  no2 = _format_number(features.get("no2_ppb"), 1)
  o3 = _format_number(features.get("o3_ppb"), 1)
  co = _format_number(features.get("co_ppm"), 2)

  lines = [
    "Alert. Potential wildfire detected near monitored sensors.",
    f"Confidence level {confidence:.0%}.",
    f"Particulate matter readings: PM two point five {pm25}, PM ten {pm10}.",
    f"Air quality index {aqi}.",
    f"Temperature {temperature} degrees Fahrenheit, humidity {humidity} percent.",
    f"Wind speed {wind_speed} miles per hour.",
    (
      "Gas concentrations: nitrogen dioxide "
      f"{no2} parts per billion, ozone {o3} parts per billion, carbon monoxide {co} parts per million."
    ),
    "Please dispatch nearby crews to investigate and ensure public safety.",
    "This automated alert was generated by the UCLA wildfire detection system.",
  ]
  return " ".join(lines)


def _build_twiml(confidence: float, features: Dict[str, Any]) -> str:
  message = _build_voice_message(confidence, features)
  logger.debug("Generated Twilio voice message: %s", message)
  return (
    '<?xml version="1.0" encoding="UTF-8"?>'
    "<Response>"
    '<Say voice="alice" language="en-US">'
    f"{message}"
    "</Say>"
    '<Pause length="1"/>'
    '<Say voice="alice" language="en-US">End of message.</Say>'
    "</Response>"
  )


def maybe_send_fire_alert(
  *,
  predicted_label: str,
  confidence: float,
  features: Dict[str, Any],
) -> bool:
  client = get_twilio_client()
  if client is None:
    return False

  is_fire = predicted_label.strip().lower() == "yes"

  if not is_fire:
    logger.debug("Twilio alert suppressed: predicted label is not 'yes'.")
    return False

  if confidence <= FIRE_ALERT_THRESHOLD and confidence < 1.0:
    logger.debug(
      "Twilio alert suppressed: confidence %.3f at/below threshold %.3f.",
      confidence,
      FIRE_ALERT_THRESHOLD,
    )
    return False

  logger.info(
    "Triggering Twilio alert for fire label with confidence %.3f (threshold %.3f).",
    confidence,
    FIRE_ALERT_THRESHOLD,
  )
  logger.debug("Voice alert payload features: %s", features)

  try:
    create_kwargs = {
      "to": TWILIO_TO,
      "from_": TWILIO_FROM,
    }
    if TWILIO_VOICE_URL:
      create_kwargs["url"] = TWILIO_VOICE_URL
    else:
      create_kwargs["twiml"] = _build_twiml(confidence, features)

    if TWILIO_VOICE_STATUS_CALLBACK:
      create_kwargs["status_callback"] = TWILIO_VOICE_STATUS_CALLBACK

    call = client.calls.create(**create_kwargs)
    logger.info(
      "Twilio voice alert queued: sid=%s status=%s to=%s",
      call.sid,
      getattr(call, "status", "unknown"),
      TWILIO_TO,
    )
    try:
      refreshed = client.calls(call.sid).fetch()
      logger.debug(
        "Twilio call %s current status: %s",
        call.sid,
        getattr(refreshed, "status", "unknown"),
      )
    except TwilioException as fetch_exc:
      logger.debug("Unable to refresh Twilio call status: %s", fetch_exc)
    return True
  except TwilioException as exc:
    logger.error("Failed to initiate Twilio voice alert: %s", exc)
    return False
